apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
      - name: post-service
        image: foxxx614/posting-queue-service
        ports:
        - containerPort: 8000