apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
          - name: POSTGRES_DB
            value: user_service_db
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: user-service-db-storage
            subPath: users
      volumes:
        - name: user-service-db-storage
          persistentVolumeClaim:
            claimName: user-service-pvc