apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
      - name: template-service
        image: foxxx614/posting-template-service
        ports:
        - containerPort: 8000